name: 1. Simple Hello World Pipeline

on:
  push:
    branches: [ main ] # اجرا با هر بار پوش به شاخه اصلی

jobs:
  say_hello_job:
    runs-on: ubuntu-latest # محیط اجرا
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4 # گام ۱: دریافت کد از مخزن

      - name: 2. Print a greeting message
        run: echo "Hello World!" # گام ۲: چاپ پیام

      - name: 3. List files for verification
        run: ls -la # گام ۳: نمایش فایل‌ها در محیط اجرا