name: 1. Simple Push Pipeline

on:
  push:
    branches: [ main ]

jobs:
  say_hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4 # دریافت کد

      - name: 2. Print a greeting message
        run: echo "Hello from the Simple Automation Pipeline!"

      - name: 3. List files for verification
        run: ls -la # تایید محتوای پوشه