name: Horray

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  first_mahdi_code_ever:
    runs-on: ubuntu-latest
    env: # Define environment variables
      Sample_env_var : "Mahdi"
      Flag_var : 'true'

    steps:
      - name: 1- Checkout Variable
        if: env.Flag_var == 'true'
        run: echo "Sample_env_var is ${{ env.Sample_env_var }}"

      - name: 2- If Condition Not Met
        if: env.Flag_var != 'true'
        run: echo "Condition not met. because of flag_var value is not ${{ env.Flag_var }} and Were False"